defaultName: My Dropwizard App with MySQL

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/fruit?useSSL=false&serverTimezone=UTC
  user: oasisis
  password: Password1!
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: update
    hibernate.show_sql: true
    hibernate.format_sql: true
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1minute

logging:
  level: INFO
  loggers:
    com.example.myapp: DEBUG 
    org.hibernate.SQL: DEBUG
